<a href="https://colab.research.google.com/github/laur-park/dsci235-final-project/blob/main/Diddi_Parker_Final_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **You Are What You Can Afford: Diet, Income, and Success in College**

Lauren Parker & Isha Diddi

Professor Gaddy

DSCI 235

27 April 2026

### Introduction

Paragraph

### Part 1: Relationships Between Income, Health, Personal Beliefs, and Student Academic Performance


---

**A. Data Cleaning & Exploration**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
data1 = pd.read_csv('/cleanedfooddata.csv')
data1.head()

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,3.654,1,1,610,3,420,2,"chocolate, chips, ice cream","Stress, bored, anger",1,...,1,1,2,725,690,Basketball,4,2,900,155
1,3.300,1,1,720,4,420,2,"frozen yogurt, pizza, fast food","stress, sadness",1,...,1,2,5,1165,500,none,5,1,900,I'm not answering this.
2,3.500,1,1,720,2,420,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1,...,1,1,4,940,500,Softball,4,2,760,190
3,3.800,2,1,610,3,420,2,"Chocolate, ice cream, french fries, pretzels","stress, boredom",1,...,1,1,5,940,690,soccer,4,1,1315,180
4,3.300,1,1,720,3,420,1,"Ice cream, cheeseburgers, chips.",I eat comfort food when im stressed out from s...,1,...,1,2,1,725,500,none,4,2,1315,137

In [19]:
refer_to = pd.read_csv('/codebook (1).csv')
refer_to = refer_to.iloc[:55, :4]
refer_to.head()

,Variables,Responses,Question,Type of Variable
0,GPA,open ended,What is your GPA?,open-ended
1,Gender,1 = Female\n2 = Male,What is your gender?,interval
2,breakfast,1 = cereal option\n2 = donut option,the participants are shown the following pictu...,interval
3,calories_chicken,open ended,guessing calories in chicken piadina,interval
4,calories_day,1 - i dont know how many calories i should con...,Importance of consuming calories per day,interval

In [ ]:
# columns we will use: GPA (open-ended,0), (family) income (interval,32), fruit_day
# (interval,24), veggies_day (interval,51), employment (interval,14), diet_current
# (interval,8), exercise (interval,16)

**B. Developing a relationship between family income and the likelihood of consuming fruits and vegetables.**

In [ ]:
#data1('income')['fruit_day'].mean()
data1.pivot_table('fruit_day', index='income', columns='class')
#data1.groupby('sex')[['survived']].mean()

TypeError: 'DataFrame' object is not callable

**C. Exploring how working status may influence a student’s likelihood to consume fruit and vegetables.**

**D. Determine whether health status and GPA are correlated.**

To quantify health status, we will be using the column health_feeling. Healthy students

**E. Assess the relationship between family income and GPA.**

**F. Overall Analyses**

### Part 2: Affordability of Maintaining a Healthy Diet

---

**A. Data Cleaning & Exploration**

In [ ]:
fruity = pd.read_csv('/fruit-prices-2023 (2).csv')
fruity.head()

,Fruit,Form,AverageRetailPrice,AverageRetailPriceUnitOfMeasure,PreparationYieldFactor,SizeOfACupEquivalent,CupEquivalentUnitOfMeasure,AveragePricePerCupEquivalent
0,Apples,Fresh,1.860931,per pound,0.90,0.2425,pounds,0.501435
1,"Apples, applesauce",Canned,1.208099,per pound,1.00,0.5401,pounds,0.652534
2,"Apples, ready to drink",Juice,0.951115,per pint (16 fluid ounces ready to drink),1.00,0.5000,pints,0.475558
3,"Apples, frozen concentrate",Juice,2.668334,per pint (16 fluid ounces concentrate),4.00,0.5000,pints,0.333542
4,Apricots,Fresh,3.803732,per pound,0.93,0.3638,pounds,1.487802

In [ ]:
veggie = pd.read_csv('/vegetable-prices-2023.csv')
veggie.head()

,Vegetable,Form,AverageRetailPrice,AverageRetailPriceUnitOfMeasure,PreparationYieldFactor,SizeOfACupEquivalent,CupEquivalentUnitOfMeasure,AveragePricePerCupEquivalent
0,Acorn squash,Fresh,1.241439,per pound,0.4586,0.4519,pounds,1.223533
1,Artichoke,Fresh,2.506856,per pound,0.3750,0.3858,pounds,2.080461
2,Artichoke,Canned,3.505101,per pound,0.6500,0.3858,pounds,2.579113
3,Asparagus,Fresh,3.212453,per pound,0.4938,0.3968,pounds,2.581436
4,Asparagus,Canned,3.676296,per pound,0.6500,0.3968,pounds,2.244419

**B.  Estimating the cost per serving of fruit**

**C. Estimating the cost per serving of vegetables**

**D. Overall Analyses**

### Conclusion